In [2]:
from sympy import *
from sympy.abc import *
from IPython.display import display
from sympy.interactive import printing
import numpy as np
import math
printing.init_printing(pretty_print=True,use_latex=True)
var('x1 x2 y1 y2 z1 z2 q k v n t g e s')
bonds=[x1,y1,z1,x2,y2,z2]

In [3]:
#Derivatives of harmonic oscillator (for sanity) as well as the expected energy, gradient and Hessian for a
#harmonic oscillator at the point q={3.0,2.0,1.0} with parameters k={6.0,7.0,8.0} and r0={1.5,1.0,0.5}
ho=1.0/2.0*k*(q-t)**2
display(ho)
dedq=diff(ho,q)
display(dedq)
de2dq2=diff(dedq,q)
display(de2dq2)
f=lambdify([k,q,t],ho,"numpy")
print("Energy is:",sum(f(np.array([6.0,7.0,8.0]),np.array([3.0,2.0,1.0]),np.array([1.5,1.0,0.5]))))
f=lambdify([k,q,t],dedq,"numpy")
print("Gradient is:",f(np.array([6.0,7.0,8.0]),np.array([3.0,2.0,1.0]),np.array([1.5,1.0,0.5])))
f=lambdify([k,q,t],de2dq2,"numpy")
print("Diagonal of Hessian is:",f(np.array([6.0,7.0,8.0]),np.array([3.0,2.0,1.0]),np.array([1.5,1.0,0.5])))

             2
0.5⋅k⋅(q - t) 

0.5⋅k⋅(2⋅q - 2⋅t)

1.0⋅k

Energy is: 11.25
Gradient is: [ 9.  7.  4.]
Diagonal of Hessian is: [ 6.  7.  8.]


In [4]:
#Derivatives of Coulomb's law as well as the expected energy, gradient and Hessian for a
#point charges at the point q={3.0,2.0,1.0} with parameters t={6.0,7.0,8.0}
cl=t/q
display(cl)
dedq=diff(cl,q)
display(dedq)
de2dq2=diff(dedq,q)
display(de2dq2)
f=lambdify([t,q],cl,"numpy")
print("Energy is:",sum(f(np.array([6.0,7.0,8.0]),np.array([3.0,2.0,1.0]))))
f=lambdify([t,q],dedq,"numpy")
print("Gradient is:",f(np.array([6.0,7.0,8.0]),np.array([3.0,2.0,1.0])))
f=lambdify([t,q],de2dq2,"numpy")
print("Diagonal of Hessian is:",f(np.array([6.0,7.0,8.0]),np.array([3.0,2.0,1.0])))

t
─
q

-t 
───
  2
 q 

2⋅t
───
  3
 q 

Energy is: 13.5
Gradient is: [-0.66666667 -1.75       -8.        ]
Diagonal of Hessian is: [  0.44444444   1.75        16.        ]


In [5]:
#Derivatives of Fourier Series as well as the expected energy, gradient and Hessian for a
#amps={3.2,2.2,1.2}, phases={PI/2.0,PI,PI/4} periods={2.0,3.0,4.0} and angles={2.0,3.10,0.6}
fs=v*(1.0+cos(n*t-g))
display(fs)
dedt=diff(fs,t)
display(dedt)
de2dt2=diff(dedt,t)
display(de2dt2)
angles,amps,periods,phases=np.array([2.0,3.10,0.6]),np.array([3.2,2.2,1.2]),\
                           np.array([2.0,3.0,4.0]),np.array([math.pi/2.0,math.pi,math.pi/4.0])
f=lambdify([v,n,t,g],fs,"numpy")
print("Energy is:",sum(f(amps,periods,angles,phases)))
f=lambdify([v,n,t,g],dedt,"numpy")
print("Gradient is:",f(amps,periods,angles,phases))
f=lambdify([v,n,t,g],de2dt2,"numpy")
print("Diagonal of Hessian is:",f(amps,periods,angles,phases))

v⋅(cos(g - n⋅t) + 1.0)

n⋅v⋅sin(g - n⋅t)

  2               
-n ⋅v⋅cos(g - n⋅t)

Energy is: 6.30857792951
Gradient is: [-4.18331917  0.8213992  -4.79539532]
Diagonal of Hessian is: [  9.68707194 -19.64606144   0.84079682]


In [6]:
#Derivatives of Lennard Jones as well as the expected energy, gradient and Hessian for a
#r={3.2,2.2,1.2}, sigma={PI/2.0,PI,PI/4} epsilon={2.0,3.0,4.0}
lj=e*((s/q)**12-2*(s/q)**6)
display(lj)
dedq=diff(lj,q)
display(dedq)
de2dq2=diff(dedq,q)
display(de2dq2)
dist,epsilon,sigma=np.array([3.2,2.2,1.2]),np.array([2.0,3.0,4.0]),np.array([math.pi/2.0,math.pi,math.pi/4.0])
f=lambdify([e,s,q],lj,"numpy")
print("Energy is:",sum(f(epsilon,sigma,dist)))
f=lambdify([e,s,q],dedq,"numpy")
print("Gradient is:",f(epsilon,sigma,dist))
f=lambdify([e,s,q],de2dq2,"numpy")
print("Hessian is:",f(epsilon,sigma,dist))

  ⎛     6    12⎞
  ⎜  2⋅s    s  ⎟
e⋅⎜- ──── + ───⎟
  ⎜    6     12⎟
  ⎝   q     q  ⎠

  ⎛    6       12⎞
  ⎜12⋅s    12⋅s  ⎟
e⋅⎜───── - ──────⎟
  ⎜   7      13  ⎟
  ⎝  q      q    ⎠

  ⎛      6        12⎞
  ⎜  84⋅s    156⋅s  ⎟
e⋅⎜- ───── + ───────⎟
  ⎜     8       14  ⎟
  ⎝    q       q    ⎠

Energy is: 164.162849653
Gradient is: [  1.03457493e-01  -1.03778526e+03   2.89706016e+00]
Hessian is: [ -2.23560931e-01   6.51078520e+03  -1.56637591e+01]


In [23]:
#Derivatives of distance
dist=sqrt((x1-x2)**2+(y1-y2)**2+(z1-z2)**2)
r1,r2,r3=np.array([0.0,0.0,0.0]),np.array([0.85,0.1,0.0]),np.array([0.1,0.74,0.0])
r12,r13=r1-r2,r1-r3
f=lambdify([x1,y1,z1,x2,y2,z2],dist,"numpy")
qs_=f(np.array([r1[0],r1[0]]),np.array([r1[1],r1[1]]),np.array([r1[2],r1[2]]),
      np.array([r2[0],r3[0]]),np.array([r2[1],r3[1]]),np.array([r2[2],r3[2]]))
print("Distances are",qs_)

dx,dy,dz=symbols('dx dy dz')
drdq=[diff(dist,i).subs(dist,q).subs(x1-x2,dx).subs(y1-y2,dy).subs(z1-z2,dz) for i in bonds]
display(drdq)

f=lambdify([dx,dy,dz,q],drdq,"numpy")
dq1=np.array([f(r12[0],r12[1],r12[2],qs_[0]),f(r13[0],r13[1],r13[2],qs_[1])])
print("1st deriv is:",dq1)
###Hessian
dr2dqdq=[[diff(diff(dist,i),j).subs(dist,q).subs(x1-x2,dx).subs(y1-y2,dy).subs(z1-z2,dz) for j in bonds] for i in bonds]
display(dr2dqdq)

f=lambdify([dx,dy,dz,q],dr2dqdq,"numpy")
dq2=np.array([f(r12[0],r12[1],r12[2],qs_[0]),f(r13[0],r13[1],r13[2],qs_[1])])
print("2nd deriv is:",dq2)

Distances are [ 0.85586214  0.74672619]


⎡dx  dy  dz  -dx   -dy   -dz ⎤
⎢──, ──, ──, ────, ────, ────⎥
⎣q   q   q    q     q     q  ⎦

1st deriv is: [[-0.9931506  -0.11684125  0.          0.9931506   0.11684125 -0.        ]
 [-0.1339179  -0.99099243  0.          0.1339179   0.99099243 -0.        ]]


⎡⎡    2                          2                  ⎤  ⎡             2        
⎢⎢  dx    1  -dx⋅dy   -dx⋅dz   dx    1  dx⋅dy  dx⋅dz⎥  ⎢-dx⋅dy     dy    1  -d
⎢⎢- ─── + ─, ───────, ───────, ─── - ─, ─────, ─────⎥, ⎢───────, - ─── + ─, ──
⎢⎢    3   q      3        3      3   q     3      3 ⎥  ⎢    3        3   q    
⎣⎣   q          q        q      q         q      q  ⎦  ⎣   q        q         

                2           ⎤  ⎡                      2                      2
y⋅dz   dx⋅dy  dy    1  dy⋅dz⎥  ⎢-dx⋅dz   -dy⋅dz     dz    1  dx⋅dz  dy⋅dz  dz 
─────, ─────, ─── - ─, ─────⎥, ⎢───────, ───────, - ─── + ─, ─────, ─────, ───
  3       3     3   q     3 ⎥  ⎢    3        3        3   q     3      3     3
 q       q     q         q  ⎦  ⎣   q        q        q         q      q     q 

    ⎤  ⎡  2                        2                      ⎤  ⎡         2      
   1⎥  ⎢dx    1  dx⋅dy  dx⋅dz    dx    1  -dx⋅dy   -dx⋅dz ⎥  ⎢dx⋅dy  dy    1  
 - ─⎥, ⎢─── - ─, ─────, ─────, - ─── + ─, ───────,

2nd deriv is: [[[ 0.01595102 -0.1355837   0.         -0.01595102  0.1355837  -0.        ]
  [-0.1355837   1.15246145  0.          0.1355837  -1.15246145 -0.        ]
  [ 0.          0.          1.16841248 -0.         -0.         -1.16841248]
  [-0.01595102  0.1355837  -0.          0.01595102 -0.1355837   0.        ]
  [ 0.1355837  -1.15246145 -0.         -0.1355837   1.15246145  0.        ]
  [-0.         -0.         -1.16841248  0.          0.          1.16841248]]

 [[ 1.31516212 -0.17772461  0.         -1.31516212  0.17772461 -0.        ]
  [-0.17772461  0.02401684  0.          0.17772461 -0.02401684 -0.        ]
  [ 0.          0.          1.33917896 -0.         -0.         -1.33917896]
  [-1.31516212  0.17772461 -0.          1.31516212 -0.17772461  0.        ]
  [ 0.17772461 -0.02401684 -0.         -0.17772461  0.02401684  0.        ]
  [-0.         -0.         -1.33917896  0.          0.          1.33917896]]]
1.3151621207 ,-0.177724610906 ,0.0 ,-1.3151621207 ,0.177724610906 ,-0.